### ISSUE TITLE
Socket buffer overrun

### ISSUE THREAD

**Issue by nrusch** [Nvizible/NukeExternalControl#1]
This seems like it would be a fairly rare case, but if the server tries to return a pickle string that's too long, the client will hang indefinitely, or throw an "insecure pickle string" exception (which I assume just indicates the object is getting truncated in transit).

The easiest way to reproduce this is to start a session of Nuke that has the REDSpace root LUT active, and try printing nuke.root() from a client connection. This output should be somewhere in the neighborhood of 25,000 characters before pickling.

import nukeCommandClient
conn = nukeCommandClient.NukeConnection()
nuke = conn.nuke
print nuke.root()

I took a brief stab at writing a fix, but I don't know enough about socket programming to really get anywhere quickly.

**Comment by HughMacdonald** [comment]
I've just pushed a change that should fix this one.

Now, if the pickled data is larger than a defined amount (16384 bytes, by default), it'll split it up into chunks.
The first return from the server will be of the form:
{'type': "NukeTransferPartialObject", 'part': 0, 'part_count': 7, 'data': data}

Then the client will send a new request through:
{'type': "NukeTransferPartialObjectRequest", 'part': 1}

To which the server will return the next part. This will continue up to 'part_count'. Then everything in 'data' will be combined, and unpickled.

There may well still be issues the other way - if too much data is sent _to_ Nuke, the same crash will probably still happen. I just need to implement this the other direction.

**Comment by HughMacdonald** [comment]
This is properly fixed now - you can now send unlimited amounts of data in both directions.
