### ISSUE TITLE
 nuke.scriptClear() not working

### ISSUE THREAD

**Issue by sebastianelsner** [Nvizible/NukeExternalControl#2]
Hey,

running this script works fine the first time:

import nukeCommandClient
conn = nukeCommandClient.NukeConnection()
nuke = conn.nuke

root = nuke.Root()
root["first_frame"].setValue(1)
root["last_frame"].setValue(2)

nuke.scriptClear()

the second time (with the same nuke instance open) it stops working. The critical step seems to be the scriptClear, which does something to nuke so it will return a wrong value. If removed the script works when executed multiple times. Using Nuke 6.1v2 and latest head.

Cheers

Sebastian

**Comment by dbr** [comment]
I seem to recall there was a bug in Nuke where calling `nuke.scriptClear()` broke accessing `nuke.root()` - can't check just now, but I think it was fixed in 6.2 at some point

**Comment by sebastianelsner** [comment]
Thanks for the hint. 6.2 works correctly.
