### ISSUE TITLE
ImportError: No module named nukeExternalControl.client

### ISSUE THREAD

**Issue by singhaidotnish** [Nvizible/NukeExternalControl#6]
as suggested here, https://github.com/Nvizible/NukeExternalControl, I have set NUKE_PATH and even PYTHONPATH,  however still get error. How is it possible to run this successfully

**Comment by bushpig** [comment]
did you create an init.py file in the NukeExternalControl folder?

**Comment by singhaidotnish** [comment]
For now have found another work around. So, though i should have seen how to make this working, will stop now and follow up at some point later as needed
